### ISSUE TITLE
Internet: Not connected

### ISSUE THREAD

**Issue by Atikeen** [aLeX1443/SmartMine#28]
App constantly loses connection even if there are no problems with it. When I hit ‘Run’ it shows the price of Bitcoin in the lower panel but doesn’t start mining. Log says that it needs an Internet connection. But sites open well, ping works. I tried to reset WiFi router and reboot the system - at times that helps but now it’s dead. Not connected and that’s it. Using v0.5b on Win 10x64 over WiFi.

**Comment by Atikeen** [comment]
Sorry, it’s v0.5 beta 2.

**Comment by Atikeen** [comment]
Now works again.

**Comment by Atikeen** [comment]
And it doesn’t again, while web surfing and mining started manually works good. Weird.

**Comment by aLeX1443** [comment]
Beta 3 is out, and some changes were made to Internet detection. Hopefully that fixes any issues you were having

**Comment by Atikeen** [comment]
Didn’t work. Still loses connection while manual mining works. Tries to wait for connection but fails even if there is a connection in fact. I thought that might be because of GBX not officially supported, removed it, but that did not solve the problem. Connection disappears and appears back just so.
Second one is detecting low power again even if manually started mining has no issues.

**Comment by aLeX1443** [comment]
By GBX do you mean you set the currency to GBP in Settings? Is there anything in the Coin Statistics table? Could you please also attach your application log if possible (it can be found under logs/app/smart_mine_log)

**Comment by Atikeen** [comment]
No, GBX is GoByte coin. I thought pool was misconfigured but it's not the case.

gobyte = {'tag': 'GBX', 'name': 'GoByte', 'mine': True, 'exe': 'ccminer-klaust\\miner.exe', '-a': 'neoscrypt', '-o': 'stratum+tcp://eu1.altminer.net:10000', '-u': 'ADDRESS', '-p': 'c=GBX', '-i': None, '-N': None}

Manual mining .bat works OK:
miner.exe -a neoscrypt -o stratum+tcp://eu1.altminer.net:10000 -u ADDRESS -p c=GBX

I checked the logs - nothing interesting:
2018-01-15 04:59:41 app_logger INFO Started mining: GBX-GoByte
2018-01-15 05:00:28 app_logger INFO Profitability stats updated.
2018-01-15 05:01:29 app_logger INFO Profitability stats updated.
2018-01-15 05:02:30 app_logger INFO Profitability stats updated.
2018-01-15 05:03:32 app_logger INFO Profitability stats updated.
2018-01-15 05:04:33 app_logger INFO Profitability stats updated.
2018-01-15 05:05:34 app_logger INFO Profitability stats updated.
2018-01-15 05:06:35 app_logger INFO Profitability stats updated.
2018-01-15 05:07:36 app_logger INFO Profitability stats updated.
2018-01-15 05:08:37 app_logger INFO Profitability stats updated.
2018-01-15 05:08:47 app_logger INFO Not connected to the Internet
2018-01-15 05:08:47 app_logger INFO Waiting for reconnect...

Like this. Just stops and after some quits and launches again it says Internet: connected but log shows nothing. I haven't yet tried it over a wired connection. May be it's because of WiFi but at the same time all other stuff works.

**Comment by aLeX1443** [comment]
GoByte is currently not supported. Unfortunately, adding coins isn't as simple as adding a line in the config.ini, as changes need to be made to the source code when adding new coins etc. We will be bringing this coin, along with others in a later version.

I would recommend using a wired connection to help with packet loss, but there's no reason why a strong WiFi signal wouldn't work (We have some test rigs running on WiFi).

**Comment by Atikeen** [comment]
Anyway, thanks for the app. It’s a lot easy to configure and use than any of a kind.

**Comment by Atikeen** [comment]
*A lot easier.

**Comment by Atikeen** [comment]
Just a remark: when it “disconnects” it doesn’t stop miner as I mentioned before. I see now that Coin statistics stops refreshing so the last profitable coin keeps being mined. GPU info also stops refreshing showing the last data before “disconnection”.

**Comment by Atikeen** [comment]
Wired connection didn’t help. Still loses connection and can’t start mining even after restarting app.

**Comment by aLeX1443** [comment]
Beta 6 should be releasing in a few days, where some further changes were made to the way SmartMine reacts to the internet not being accessible. I can't guarantee it will fix your issue, but it's would be worth updating just in case

**Comment by Atikeen** [comment]
2018-02-02 01:16:15 app_logger INFO Switching miner
2018-02-02 01:16:16 app_logger ERROR Failed stop_mining call. Original error message: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
Traceback (most recent call last):
  File "SmartMine.py", line 574, in stop_mining
  File "C:\Users\Alex\Dropbox\Shared with MacBook Pro\Pycharm Projects\SmartMineA\src\Utils.py", line 29, in kill_miner
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
2018-02-02 01:16:16 app_logger INFO Started mining: CRC-Crowdcoin
2018-02-02 01:17:17 app_logger INFO Profitability stats updated
2018-02-02 01:18:21 app_logger INFO Profitability stats updated
2018-02-02 01:19:25 app_logger INFO Profitability stats updated
2018-02-02 01:20:29 app_logger INFO Profitability stats updated
2018-02-02 02:23:05 app_logger INFO Profitability stats updated
2018-02-02 02:24:07 app_logger INFO Profitability stats updated
2018-02-02 02:25:08 app_logger INFO Profitability stats updated
2018-02-02 02:26:14 app_logger INFO Profitability stats updated
2018-02-02 02:27:17 app_logger INFO Profitability stats updated
2018-02-02 02:28:19 app_logger INFO Profitability stats updated
2018-02-02 02:28:57 app_logger ERROR Failed __stop_mining call. Original error message: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
Traceback (most recent call last):
  File "SmartMine.py", line 606, in stop_mining1
  File "C:\Users\Alex\Dropbox\Shared with MacBook Pro\Pycharm Projects\SmartMineA\src\Utils.py", line 29, in kill_miner
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
2018-02-02 02:28:57 app_logger INFO Starting dev mining
2018-02-02 02:29:20 app_logger INFO Profitability stats updated
2018-02-02 02:30:22 app_logger INFO Profitability stats updated
2018-02-02 02:30:57 app_logger INFO Finished dev mining
2018-02-02 02:30:57 app_logger ERROR Failed stop_mining call. Original error message: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
Traceback (most recent call last):
  File "SmartMine.py", line 574, in stop_mining
  File "C:\Users\Alex\Dropbox\Shared with MacBook Pro\Pycharm Projects\SmartMineA\src\Utils.py", line 29, in kill_miner
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
2018-02-02 02:30:58 app_logger INFO Started mining: CRC-Crowdcoin

**Comment by Atikeen** [comment]
I get this periodically.

**Comment by aLeX1443** [comment]
It looks like there's an issue with stopping the miner. We haven't experienced this in testing, but we'll look into what might be causing it. Did the error impact mining? It's possible that the first `stop_mining` call failed, but the second attempt was successful.

**Comment by Atikeen** [comment]
Unfortunately I quit, because the very first launch of beta 6 showed ‘not connected’ right away. Had to switch to another app. Anyway, good luck, guys.

**Comment by aLeX1443** [comment]
Thanks for the feedback, I would recommend using a wired network instead of WiFi
